repos:
- repo: http://172.23.111.253:3000/mirror/ruff-pre-commit
  # Ruff version.
  rev: v0.2.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: http://172.23.111.253:3000/mirror/pip-tools
  rev: 7.3.0
  hooks:
  - id: pip-compile
    name: pip-compile dev-requirements.in
    args: [--no-emit-index-url,--no-emit-trusted-host, requirements/dev-requirements.in]
    files: ^requirements/dev-requirements\.(in|txt)$
  - id: pip-compile
    name: pip-compile requirements.in
    args: [--no-emit-index-url,--no-emit-trusted-host, requirements/requirements.in]
    files: ^requirements/requirements\.(in|txt)$
