[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

# [tool.pytest.ini_options]
# addopts = [
#     "--import-mode=importlib",
# ]
# pythonpath = [
#   "src"
# ]