[default]
LOG_FILE = "log/debug.log"
APP_NAME = "reportservice"
HOST = "0.0.0.0"
PORT = 3002
DEBUG_MODE = true

DB_URL = "mongodb://foo:password@localhost:27017/general?authSource=admin&retryWrites=true&w=majority"
DB_NAME = "FaceID"
DB_COLLECTION_REPORT = "BodyFaceName"

[production]
DB_URL = "mongodb://dat:password@mongo:27017/general?authSource=admin&retryWrites=true&w=majority"
DEBUG_MODE = false