version: "3.10"

services:
  reportservice:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: dat.local:5001/reportservice:0.2.0
    environment:
      # - DYNACONF_DB_URL = "" # Change database uri if needed
      - DYNACONF_PORT = 3002
    ports:
      - 3003:3002
    # volumes:
      # - ./.secret.toml:/usr/src/app/.secret.toml:ro # For secrets if needed
    restart: unless-stopped
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/connection-status"]
      start_period: 30s
      interval: 10s
      timeout: 20s
      retries: 3
