version: '3.10'

volumes:
  mongo-persistent:


services:
  fastapi:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: dat.local:5001/reportservice:0.0.1
    environment:
      - DYNACONF_DB_URL = "mongodb://foo:password@mongo:27017/general?authSource=admin&retryWrites=true&w=majority"
      - DYNACONF_DB_NAME = "reportservice"
      - DYNACONF_PORT = 3002
    ports:
      - 3003:3002
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0-focal
    restart: always
    volumes:
      - mongo-persistent:/data/db
    # ports:
      # - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: foo
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: general

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 28081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: foo
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: "mongodb://foo:password@mongo:27017/general?authSource=admin"
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
